charactersLORA = {
    "ABBY": "<lora:stAbby:.5> , tAbby, black_hair, brown_eyes, long_hair, forehead, parted_bangs, large_breasts, mature_woman",
    "ALLISON": "<lora:stAllison2:.5>,  stAllison2, huge_breasts, blonde_hair, purple_eyes, braids, hairpin",
    "AMY": "<lora:stAmy:.5>, stAmy, 1girl, short_hair, blue_eyes, brown_hair, flat_chest, bangs, eyebrows_visible_through_hair,  hair_between_eyes, neck_ribbon, bow",
    "ANUJA": "<lora:stAnuja:.5> , stAnuja, indian, 1girl, forehead, green_hair, red_eyes, long_hair,single braid, dark_skinned_female",
    "AUDREY": "<lora:stAudrey:.5>, stAudrey, person, long_hair, blue_eyes, brown_hair, multicolored_hair, two_side_up, medium_breasts, hair intakes, sidelocks",
    "BRAD": "<lora:stBrad:.5>, stBrad, 1boy, blonde_hair, red_eyes, muscular, abs, spiked_hair, earrings",
    "BREE": "<lora:stBradGB:.5>, stBradGB, blonde_hair, red_eyes, short_hair, forehead, hairpin, petite, small_breasts",
    "CARRIE": "<lora:stCarrie:.5>, stCarrie, brown_hair, red_eyes, medium_breasts, twintails",
    "CASSIE": "<lora:stCassie:.5>, stCassie, blonde_hair, long_hair, blue_eyes, large_breasts",
    "CLAUS": "<lora:stClaus:.5>, stClaus, silver_hair, yellow_eyes, short_hair, 1boy",
    "CONNIE": "<lora:stConnie:.5>, stConnie, brown_hair, red_eyes, straight_hair, mature_woman, wide_hips, large_breasts",
    "CORNY": "<lora:stCorny:.5>, stCorny, green_eyes, orange_hair, long_hair, twintails, twin_drills, petite, small_breasts, skirt, pleated_skirt, red_skirt",
    "DONNA": "<lora:stDona:.5>, stDona, brown_hair, blue_eyes, fat",
    "ELIZABETH": "<lora:stElizabeth:.5>, stElizabeth, brown_hair, brown_eyes, large breasts, bangs, long hair, ",
    "EMILY": "<lora:stEmily:.5>, stEmily, short_hair, pink_hair, yellow_eyes, small_breasts, messy_hair",
    "ERIC-BOY": "<lora:stEric:.5>, stEric, black_hair, red_eyes, muscular, short_hair, 1boy",
    "ERIC-GIRL": "<lora:stEricGB:.5>, stEricGB, black_hair, red_eyes, long_hair, large_breasts",
    "FLAVIA": "<lora:stFlavia2:.5>, stFlavia, blonde_hair, blue_eyes, large_breasts, ahego",
    "GABE": "<lora:stGabriel:.5>, stGabe, short_hair, purple_hair, yellow_eyes, messy_hair, 1boy",
    "GENNY": "<lora:stGenny:.5>, stGenny, blue_hair, yellow_eyes, medium_breasts, long_hair",
    "HOLLY": "<lora:stHolly2:.5>, stHolly, blue_hair, yellow_eyes, short_hair, medium_breasts",
    "IRENE": "<lora:stIrene:.5>, stIrene, silver_hair, blue_eyes, straight_hair, hair_ornament, large_breasts",
    "IZUNA": "<lora:stIzuna:.5>, stIzuna, blue_hair, yellow_eyes, cat_ears. large_breasts",
    "JACK": "<lora:stJack:.5>, stJack, brown_hair, red_eyes, short_hair, 1boy",
    "JANE": "<lora:stJane2:.5>, stJane, black_hair, black_eyes, large_breasts, long_hair",
    "JOHN": "<lora:stJohn:.5>, stJohn, black_hair, black_eyes, pants, blue_pants, 1boy",
    "KATRINA": "<lora:stKatrina2:.5>, stKatrina, orange_hair, short_hair, messy_hair, green_eyes, medium_breasts, skirt, pleated_skirt, red_skirt",
    "KIYOSHI-GIL": "<lora:stKiyo:.5>, stKiyo, purple_hair, red_eyes, long_hair, very_long_hair, small_breasts",
    "KIYOSHI-BOY": "<lora:stKiyoshi:.5>, stKiyoshi, purple_hair, purple_eyes, 1boy",
    "KYOKO": "<lora:stKyoko:.5> , stKyoko, blue_eyes, maroon_hair, hair_ornament, medium_breasts, short_hair",
    "LEONA": "<lora:stLeona:.5>, grey_hair, wavy_hair, long_hair, brown_eyes, yellow_eyes, large_breasts, skirt, pleated_skirt, red_skirt",
    "MARIA": "<lora:stMaria:.5>, stMaria, brown_hair, red_eyes, medium_hair, hairband, hair flower, facepaint, small breasts, petite, forehead",
    "MAURICE": "<lora:stMaurice:.5>, stMaurice, 1boy, purple_hair, blue_eyes, short_hair, mature male, 1boy",
    "MEL": "<lora:stMel:.5>, stMel, blue_hair, short_hair, ahegao, yellow_eyes, petite, large_breasts",
    "MICHELLE": "<lora:stMichelle:.5>, stMichelle, brown_hair, brown_eyes, medium_hair, large_breasts",
    "PHILA": "<lora:stMina+stPhila:.5>, stPhila, blond_hair, gradient_hair, pink_hair, green_eyes, red_eyes, heterochromia, long_hair, wavy hair,  medium_breasts, headband, red_headband, forehead, hair slicked back",
    "MINA": "<lora:stMina+stPhila:.5>, stMina, blond_hair, gradient_hair, pink_hair, green_eyes, red_eyes, heterochromia, long_hair, wavy hair,  medium_breasts, headband, blue_headband, forehead, hair slicked back",
    "RACHEL": "<lora:stRachel:.5>, stRachel, black_hair, long_hair, blue_eyes, red_lips, lips, large_breasts, mature_female",
    "RILEY": "<lora:stRiley2:.5>, stRiley, brown_hair, brown_eyes, 1boy",
    "RITA": "<lora:stRita:.5>, pink_hair, blue_eyes, twin_tails, twin drills, hair_ribbon",
    "SADIE": "<lora:stSadie2:.5>, stSadie, pink_hair, blue_eyes, large_breasts, ponytail",
    "SANDRA": "<lora:stSandra2:.4> , stSandra, pink_hair, blue_eyes, mole_under_eye, large_breasts, wide_hips, mature_female, short_hair",
    "SAYAKA": "<lora:stsayaka:.5>, stSayaka, pink_hair, blue_eyes, large_breasts, headband, skirt, pleated_skirt, red_skirt",
    "SCARLET": "<lora:stScarlet:.5>, stScarlet, red_hair, brown_eyes, medium_breasts, long_hair, sidelocks",
    "SETSUNA": "<lora:stSetsuna:.5>, stSetsuna, aqua_hair, blue_eyes, medium_breasts, braid",
    "TORI": "<lora:stTori:.5> stTori, grey_hair, yellow_eyes, folded_ponytail, hair_ornament, (((hair over one eye))), large_breasts, medium_hair",
    "YUI": "<lora:stYui:.5>, stYui, purple_hair, purple_eyes, long_hair, red_ribon, hair_ribon, large_breasts",
    "YUUNA": "<lora:stYuuna:.5>, stYuuna, purple_hair, blue_eyes, ponytail, long_hair, mature_female, wide_hips",
    "ZOEY": "<lora:stZoey2:.4> , stZoey, blonde_hair, green_eyes, medium_hair, single_braid, petite, small_breasts",
    "VANESSA": "<lora:inase_kohane:.7>, inasekohane_tk, long hair, blue_eyes, red_hair, side_ponytail, large breasts, chocker",
    "TKUNIFORM": " <lora:STUniform:.4>, blue_vest, white_shirt, short_sleeves, red_necktie, red_skirt, pleated_skirt"
}