ComfyList = {
    "ABBY": "lora_2|stAbby,1girl,(black_hair:1.2),(dark green_hair:0.7),red_eyes,parted bangs,long bangs,double-parted bangs,ponytail,large_breasts,mature female,aged up",
    "ALEX": "lora_3|stAlex,1girl,bangs,silver hair,yellow eyes,large_breasts,bespectacled,black-framed_eyewear,eyebrows_visible_through_hair,glasses,over-rim_eyewear,semi-rimless_eyewear,short_hair,under-rim_eyewear,mature female,aged up",
    "AMY": "lora_4|stAmy,1girl,brown_hair,blue_eyes,bangs,eyebrows_visible_through_hair,short_hair,small_breasts",
    "ANUJA": "lora_5|stAnuja,1girl,dark green_hair,brown_eyes,bangs,braid,dark-skinned_female,dark_skin,face,long_hair,single_braid,forehead_mark,indian",
    "AUDREY_IDOL": "lora_6|stAudreyIdol,1girl,green_eyes,pink_hair,breasts,choker,gloves,idol,large_breasts,short_hair,white_gloves,straps,pink_dress,cleavage,bare_shoulders,hair flower,frilled dress",
    "BRAD": "lora_49|stBrad,1boy,blonde_hair,red_eyes,short_hair,spiked hair",
    "BREE": "lora_7|stBradGB,1girl,collarbone,hair_ornament,hairclip,layered_skirt,polka_dot,polka_dot_shirt,polka_dot_skirt,shirt,short_hair,simple_background,skirt,solo,star_print,blonde hair,red eyes,forehead,hairpin",
    "CARRIE": "lora_8|stCarrie,1girl,brown_hair,red_eyes,bangs,eyebrows_visible_through_hair,glasses,long_hair,round_eyewear,semi-rimless_eyewear,twintails",
    "CASSIE": "lora_9|stCassie,1girl,blue_eyes,blonde_hair,bangs,eyebrows_visible_through_hair,hair_between_eyes,hair_intakes,long_hair",
    "CIRCE": "lora_10|stCirce,1girl,long_fingernails,long_hair,medium_breasts,nail_polish,purple_nails,sharp_fingernails,solo,very_long_fingernails,lamia,(((snake tail))),monster_girl,slit_pupils,angry,fangs,colored_skin,(demon horns),scales",
    "CONNIE": "lora_11|stConnie,1girl,browm_hair,long_hair,straight_hair,red_eyes,mature_female,aged_up,large_breasts",
    "ELIZABETH": "lora_12|stElizabeth,1girl,bangs,breasts,eyebrows_visible_through_hair,hair_bun,long_hair,sidelocks,black_hair,brown_eyes,long_hair",
    "EMILY": "lora_13|stEmily,1girl,red_hair,yellow_eyes,bangs,eyebrows_visible_through_hair,hair_between_eyes,messy_hair,short_hair,spiked_hair",
    "ERIC": "lora_15|stEric,1boy,(black_hair:1.2),red_eyes,eyebrows_visible_through_hair,hair_between_eyes,short_hair,muscular male",
    "ERICGB": "lora_14|stEricGB,1girl,(black_hair:1.2),red_eyes,eyebrows_visible_through_hair,hair_between_eyes,medium,straight_hair",
    "FLAVIA": "lora_16|stFlavia,1girl,aqua_eyes,blonde_hair,messy_hair,eyebrows_visible_through_hair,face,hair_between_eyes,long_hair",
    "GENNY": "lora_17|stGenny,1girl,blue_hair,purple_eyes,bangs,eyebrows_visible_through_hair,aged_down",
    "IRENE": "lora_18|stIrene,1girl,silver_hair, blue_eyes, bangs,eyebrows_visible_through_hair,face,hair_ornament,long_hair, straight_hair, huge_breasts",
    "IZUNA": "lora_19|stIzuna,1girl,blue_hair,yellow_eyes,cat_ear-shaped_hair,long_hair,medium_breasts,very_long_hair,scowl",
    "JACK": "lora_20|stJack,1boy,brown_hair,brown_eyes,glasses,short_hair mature male,skinny,suite,collared_shirt,necktie",
    "JANE": "lora_21|stJane,1girl,large_breasts,(black_hair:1.2),straight_hair,long_hair,(black_eyes:1.3),low ponytail,hair bow",
    "KATRINA": "lora_22|stKatrina,1girl,orange_hair,green_eyes,medium_breasts",
    "KIYO": "lora_23|stKiyo,1girl,purple_hair,very_long_hair,purple_eyes,glasses,small_breasts,skinny",
    "KIYOSHI": "lora_24|stKiyoshi,1boy,purple_hair,very_short_hair,purple_eyes,glasses,skinny",
    "KYOKO": "lora_25|stKyoko,1girl,maroon_hair,red_hair,aqua_eyes,glasses,red-framed eyewear,semi-rimless eyewear,eyebrows_visible_through_hair,hair_between_eyes,hair_intakes,hair_ornament,hair_ribbon,ribbon",
    "LAURA": "lora_26|stLaura,1girl,very_short_hair,bangs,eyebrows_visible_through_hair,hair_between_eyes,brown_hair,red_eyes,large_breasts,mature_woman,aged_up",
    "LEONA": "lora_27|stLeona,1girl,grey_hair,yellow_eyes,bangs,eyebrows_visible_through_hair,long_hair,swept_bangs,large_breasts,mature_woman,aged_up",
    "MARIA": "lora_28|stMaria,1girl,bangle,bead_bracelet,bracelet,breasts,drill_hair,facial_mark,flower,hair_flower,hair_ornament,jewelry,medium_hair,nail_polish,pearl_bracelet,tattoo,wrist_scrunchie,wristband",
    "MAURICE": "lora_29|stMaurice,1boy,black-framed_eyewear,eyebrows_visible_through_hair,glasses,over-rim_eyewear,semi-rimless_eyewear,under-rim_eyewear,mature male,aged_up",
    "MEL": "lora_30|stMel,1girl,blue_hair,ahoge,yellow_eyes,large_breasts,petite",
    "MICHELLE": "lora_31|stMichelle,1girl,brown_hair,brown_eyes,glasses,hair_ornament,hairclip,large_breasts,red-framed_eyewear,short_hair",
    "NAOMI": "lora_32|stNaomi,1girl,blue_hair,yellow_eyes,bangs,eyebrows_visible_through_hair,hair_between_eyes,short_hair,mature female,medium_breasts",
    "PHILA": "lora_33|stPhila,1girl,long_hair,wavy_hair,multicolored hair,heterochromia,green eyes,red eyes,blonde_hair,pink_hair,gradient hair",
    "MINA": "lora_33|stMina,1girl,long_hair,wavy_hair,multicolored hair,heterochromia,green eyes,red eyes,blonde_hair,pink_hair,gradient hair",
    "RILEY": "lora_34|stRiley,1boy,eyebrows_visible_through_hair,male_focus,brown_hair,brown_eyes,yellow_eyes,skinny",
    "RITA": "lora_35|stRita,1girl,drill_hair,eyebrows_visible_through_hair,hair_ornament,twin_drills,twintails,pink_hair,blue_eyes",
    "SANDRA": "lora_36|stSandra,1girl pink_hair,blue_eyes,mole under eye,short_hair,mature_woman,aged up,huge_breasts",
    "SETSUNA": "lora_37|stSetsuna,1girl,(blue_hair:1.2),purple_eyes,medium_breasts,short_hair,braid,medium_breasts",
    "TORI": "lora_38|stTori,1girl,folded_ponytail,hair_ornament,hair_over_one_eye,large_breasts,grey_hair,yellow_eyes",
    
    "ALLISON": "lora_39|stAllison, huge_breasts, blonde_hair, purple_eyes, braids, hairpin",
    "AUDREY-NORMAL": "lora_40|stAudrey, person, long_hair, blue_eyes, brown_hair, multicolored_hair, two_side_up, medium_breasts, hair intakes, sidelocks",
    "CLAUS": "lora_41|stClaus, silver_hair, yellow_eyes, short_hair",
    "CORNY": "lora_42|stCorny, green_eyes, orange_hair, long_hair, petite, small_breasts",
    "DONNA": "lora_43|stDona, brown_hair, blue_eyes, fat",
    "HOLLY": "lora_44|stHolly, blue_hair, yellow_eyes, short_hair, medium_breasts",
    "JOHN": "lora_45|stJohn, 1boy, black_hair, black_eyes, very_short_hair",
    "RACHEL": "lora_46|stRachel, black_hair, long_hair, blue_eyes, red_lips, lips, large_breasts, mature_female",
    "SAYAKA": "lora_47|stSayaka, pink_hair, blue_eyes, large_breasts",
    "SCARLET": "lora_48|stScarlet, red_hair, brown_eyes, medium_breasts, long_hair, sidelocks",
          
    "SPRITE": "lora_1|stsprtstle",    
    "TKUNIFORM": "lora_1|stsprtstle, short sleeves, red necktie, blue vest, gold trim, grey background, solo, red skirt, pleated skirt, plaid skirt, short hair, standing, white shirt, dress shirt, double-breasted, straight hair, miniskirt, school emblem",
    "QUALITY": "lora_0|score_9,score_8_up,score_7_up,score_6_up,score_5_up,score_4_up,source_anime, flat_colors",
}