LORA_List = {
    "TKUNIFORM": " <lora:STUniform:.4>, blue_vest, white_shirt, short_sleeves, red_necktie, red_skirt, pleated_skirt",
    "BE-TG": "<lora:BEReaction:.5>, <lora:Breast_Expansion:.75>, <lora:SelfBreastGrab:.75>, sbg, breast grab, breast lift, <lora:ArsEmbarrassed-t5:.5>, embarrassed, blush, looking_down",
    "PUNK": "<lora:punk_v0.2:.75> , punk, skirt, thighhighs, jewelry, earrings, boots, midriff, striped, belt, miniskirt, nail polish, collar, plaid, black shirt, chain, plaid skirt, piercing, cross, ear piercing, fishnets, black nails, striped thighhighs, spikes, black lips, (((eyeshadow))), (((black eyeshadow))), (((black lips))), lipstick, black eyeliner, fishnets, knee boots, black_boots, black_shirt",
    "SLIME-GIRL": "<lora:slimegirl3:.75> , (((slime_gir))), ((transparent)), ((see-through)), ((transparent face)), ((transparent body)), ((transparent skin)), ((colored_skin)), monster_girl",
    "SLIME-GIRL-V2": "<lora:Slimes_V01:1>, , slimes, translucent skin, water drop, bubble, ",
    "TF-SEQUENCE": "<lora:gender-transformation:.8> gender transformation, mtf, sequence, full body, standing",
    "OVERSIZED": "<lora:shrinkray_anime:.8>, oversized_clothes, clothes_on_floor, sleeves_past_wrists, pants pull, skirt pull, panty pull, off shoulder, bare shoulders",
    "BREAST-GRAB": "<lora:SelfBreastGrab:.75>, sbg, breast grab, breast lift, hand_on_own_chest, <lora:BEReaction:.5>",
    "MILF": "mature_female, wide_hips, <lora:AuntJuneV3:.5>, auntjunev3, auntjune",
    "YURI-MASTURBATION": "<lora:yuri_fingering:.7>, (((fingering_another))), 2girls, yuri, fingering, multiple_girls, couple, sex, pussy, pussy juice",
    "YURI-KISS": " <lora:npmathilda:.75>, yuri, 2girls, kiss",
    "YURI-TRIBADISM": "<lora:qqq-turi_tribadism-v2:.75>, tribadism, 2girls, yuri, sex, arm_support, breasts, nipples, nude, leg_up, multiple_girls, navel, pussy, pussy_juice, trembling",
    # "YURI-CUNNILINGUS": "<lora:lezcunbkv2:1>, lesbian cunnilingus, cunnilingus, 2girls, yuri",
    "YURI-69": "<lora:69v2:.75> , 69, yuri, 2girls",
    "POV-CUNNILINGUS": "<lora:Cunnilingus:.75>, tongue, looking at viewer,  cunnilingus, oral, female pov, pussy, spread legs, licking",
    "POV-CUNNILINGUS2": "<lora:qqq-cunnilingus_pov-v1:.75>, tongue, looking at viewer,  cunnilingus, oral, female pov, pussy, spread legs, licking",
    "MASTURBATION": "<lora:Arched back orgasm:1>, arched back, full-face blush, sweat, moaning, open mouth, masturbation, female masturbation, open mouth, aroused",
    "FURRY": "cat ears, cat tail, cat girl, slit pupils, fur, furry, <lora:lora_Furry_female:.5>",
    "MULTIPLE-GIRLS": "<lora:harem_4:1>, multiple girls, group picture",
    "SELFIE": " <lora:Selfie_FefaAIart:1>, selfie, pov, reaching_towards_viewer",
    "DILDO-MAST": "<lora:masturbation_with_dildo v1.1:1> , dildomasturbation, vaginal object insertion, female masturbation, object insertion, masturbation, nsfw, spread legs",
    "LAP-PILLOW-POV": "<lora:hizam_v02a:1>, hizam, from below",
    "WHITEBG": "(((simple_background))), (((white_background))), ((no shadows)), reference_sheet, posing",
    "QUALITY": "masterpiece, best_quality, extremely detailed, intricate, high_details, sharp_focus , best_anatomy, hires, (colorful), beautiful, 4k, magical, adorable, (extraordinary:0.6), <lora:thickline_fp16:.2>, <lora:neg4all_bdsqlsz_V3.5:1.0>, negative_hand-neg, ",
    "NEGATIVE": "fewer digits, extra body parts, censored, collage, logo, border, badhandv4, paintings, sketches, fingers, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, (outdoor:1.6), backlight,(ugly:1.331), (duplicate:1.331), (morbid:1.21), (mutilated:1.21), (tranny:1.331), mutated hands, (poorly drawn hands:1.5), blurry, (bad anatomy:1.21), (bad proportions:1.331), extra limbs, (disfigured:1.331), lowers, bad hands, missing fingers, extra digit, ",
    "CANDYSOFT": "<lora:Candysprite style:.2>, <lora:Koku_V1.0a:.2>, flat",
    "BIRTH": "(((white_background))), (((simple_background))), (((multiple_views))), (((reference_sheet)))",
    "ADD-DETAILS": "<lora:more_details:.2>",
    "ADD-MORE-DETAILS": "<lora:more_details:.4>",
    "EVEN-MORE-DETAILS": "<lora:more_details:.6>",
    "TOO-MUCH-DETAILS": "<lora:more_details:.8>",
    "HARPY1": "<lora:harpy_cpt_v01:1> , harpycpt, harpy, winged arms, bird legs, talons",
    "HARPY2": "<lora:harpy:1> , harpy, monster_girl, wings, feathers, talons",
    "WEAPON-HOLDING": "<lora:holdingweapon001:.75>",
    "WEAPON-BLADES": " <lora:KatanaOneHandV5:1>, basic grip",
    "TKCHEER": " <lora:stCheerUniform3:.75>, stCheerUniform cheerleader, red_shirt, bare_shoulders,  cleavage, collar_bone, midriff, navel, skirt, (((white_skirt))), pleated skirt, (((pom pom \(cheerleading\)))), yellow pom pom \(cheerleading\)",
    "DOWN-BLOUSE": "<lora:EDB:1> downblouse, extended downblouse, leaning_forward",
    "HEADLESS": "<lora:DisembodiedHeadV2:1.0>, DisembodiedHead, holding head, headless",
    "GENIE": "<lora:genie3:.85>, genie, genie_tail, smoke_tail, smoke, magic_lamp, glowing, smoke_tail, smoke_hair, ponytail, magic, pointy_ears, bracer, belt, gold_belt, gold_bracer, floating",

     "OUTFIT_KAT_CASUAL": "<lora:stOutfits:.6>, stOutfits, katrina_casual, shirt, (((yellow_shirt))), cleavage, collarbone, midriff, navel,  blue_shorts, brown_belt, blue bra, taut shorts, bow, stKatrina, <lora:stKatrina:.4>",
     "OUTFIT_KAT_MAID": " <lora:stOutfits:.6>, stOutfits, katrina_maid, maid, white apron, dress, thighhighs, blue_dress,  <lora:stKatrina2:.4> , stKatrina, white collar, collared dress, black thighhighs,  short sleeves",
     "OUTFIT_JANE_DRESS_AQUA": "<lora:stOutfits:.6>, stOutfits, jane_casual, dress,  (((aqua_dress))), cleavage, black_jacket, long sleeves, sleeves rolled up, black legwear,  <lora:stJane2:.5> , stJane, open jacket, aqua dress under jacket, collared",
     "OUTFIT_JANE_DRESS_WHITE": "<lora:stOutfits:.6>, stOutfits, jane_casual, dress,  (((aqua_dress))), cleavage, black_jacket, long sleeves, sleeves rolled up, black legwear,  <lora:stJane2:.5> , stJane, open jacket, aqua dress under jacket, collared",
     "OUTFITS_JOHN_CASUAL": "<lora:stJohn:.5> , stJohn, (((green hoodie))), (((open hoodie))), white shirt, (((undershirt))), pants"
}