SDXL_List = {
    "ABBY": "<lora:stAbby_XL-v1:1>, stAbby,1girl,(black_hair:1.2),(dark green_hair:0.7),red_eyes,parted bangs,long bangs,double-parted bangs,ponytail,large_breasts,mature female,aged up,",
    "ALEX": "<lora:stAlex_XL-v1:1>, stAlex,1girl,bangs,silver hair,yellow eyes,large_breasts,bespectacled,black-framed_eyewear,eyebrows_visible_through_hair,glasses,over-rim_eyewear,semi-rimless_eyewear,short_hair,under-rim_eyewear,mature female,aged up,",
    "AMY": "<lora:stAmy_XL-v1:1>, stAmy,1girl,brown_hair,blue_eyes,bangs,eyebrows_visible_through_hair,short_hair,small_breasts,",
    "ANUJA": "<lora:stAnuja_XL-v1:1>, stAnuja,1girl,dark green_hair,brown_eyes,bangs,braid,dark-skinned_female,dark_skin,face,long_hair,single_braid,forehead_mark,indian,",
    "AUDREY_IDOL": "<lora:stAudreyIdol_XL-v1:1>, stAudreyIdol,1girl,green_eyes,pink_hair,breasts,choker,gloves,idol,large_breasts,short_hair,white_gloves,straps,pink_dress,cleavage,bare_shoulders,hair flower,frilled dress,",
    "BRAD": "<lora:stBrad_XL-v1:1>, stBrad,1boy,blonde_hair,red_eyes,short_hair,spiked hair,",
    "BRADGB": "<lora:stBradGB_XL-v2:1>, stBradGB,1girl,collarbone,hair_ornament,hairclip,layered_skirt,polka_dot,polka_dot_shirt,polka_dot_skirt,shirt,short_hair,simple_background,skirt,solo,star_print,blonde hair,red eyes,forehead,hairpin,",
    "CARRIE": "<lora:stCarrie_XL-v1:1>, stCarrie,1girl,brown_hair,red_eyes,bangs,eyebrows_visible_through_hair,glasses,long_hair,round_eyewear,semi-rimless_eyewear,twintails,",
    "CASSIE": "<lora:stCassie_XL-v1:1>, stCassie,1girl,blue_eyes,blonde_hair,bangs,eyebrows_visible_through_hair,hair_between_eyes,hair_intakes,long_hair,",
    "CIRCE": "<lora:stCirce_XL-v1:1>, stCirce,1girl,long_fingernails,long_hair,medium_breasts,nail_polish,purple_nails,sharp_fingernails,solo,very_long_fingernails,lamia,(((snake tail))),monster_girl,slit_pupils,angry,fangs,colored_skin,(demon horns),scales,",
    "CONNIE": "<lora:stConnie_XL-v1:1>, stConnie,1girl,browm_hair,long_hair,straight_hair,red_eyes,mature_female,aged_up,large_breasts,",
    "ELIZABETH": "<lora:stElizabeth_XL-v1:1>, stElizabeth,1girl,bangs,breasts,eyebrows_visible_through_hair,hair_bun,long_hair,sidelocks,black_hair,brown_eyes,long_hair,",
    "EMILY": "<lora:stEmily_XL-v1:1>, stEmily,1girl,red_hair,yellow_eyes,bangs,eyebrows_visible_through_hair,hair_between_eyes,messy_hair,short_hair,spiked_hair",
    "ERIC": "<lora:stEric_XL-v1:1>, stEric,1boy,(black_hair:1.2),red_eyes,eyebrows_visible_through_hair,hair_between_eyes,short_hair,muscular male,",
    "ERICGB": "<lora:stEricGB_XL-v1:1>, stEricGB,1girl,(black_hair:1.2),red_eyes,eyebrows_visible_through_hair,hair_between_eyes,medium,straight_hair,",
    "FLAVIA": "<lora:stFlavia_XL-v1:1>, stFlavia,1girl,aqua_eyes,blonde_hair,messy_hair,eyebrows_visible_through_hair,face,hair_between_eyes,long_hair,",
    "GENNY": "<lora:stGenny_XL-v1:1>, stGenny,1girl,blue_hair,purple_eyes,bangs,eyebrows_visible_through_hair,aged_down,",
    "IRENE": "<lora:stIrene_XL-v1:1>, stIrene,1girl,silver_hair, blue_eyes, bangs,eyebrows_visible_through_hair,face,hair_ornament,long_hair, straight_hair, huge_breasts,",
    "IZUNA": "<lora:stIzuna_XL-v1:1>, stIzuna,1girl,blue_hair,yellow_eyes,cat_ear-shaped_hair,long_hair,medium_breasts,very_long_hair,scowl,",
    "JACK": "<lora:stJack_XL-v1-000005:1>,stJack,1boy,brown_hair,brown_eyes,glasses,short_hair mature male,skinny,suite,collared_shirt,necktie,",
    "JANE": "<lora:stJane_XL-v1-000006:1>,stJane,1girl,large_breasts,(black_hair:1.2),straight_hair,long_hair,(black_eyes:1.3),low ponytail,hair bow,",
    "KATRINA": "<lora:stKatrina_XL:1>, stKatrina,1girl,orange_hair,green_eyes,medium_breasts,",
    "KIYO": "<lora:stKiyo_XL-v1-000005:1>, stKiyo,1girl,purple_hair,very_long_hair,purple_eyes,glasses,small_breasts,skinny,",
    "KIYOSHI": "<lora:stKiyoshi_XL-v1-000006:1>, stKiyoshi,1boy,purple_hair,very_short_hair,purple_eyes,glasses,skinny,",
    "KYOKO": "<lora:stKyoko_XL-v1-000006:1> ,stKyoko,1girl,maroon_hair,red_hair,aqua_eyes,glasses,red-framed eyewear,semi-rimless eyewear,eyebrows_visible_through_hair,hair_between_eyes,hair_intakes,hair_ornament,hair_ribbon,ribbon,",
    "LAURA": "<lora:stLaura_XL-v1-000006:1>, stLaura,1girl,very_short_hair,bangs,eyebrows_visible_through_hair,hair_between_eyes,brown_hair,red_eyes,large_breasts,mature_woman,aged_up,",
    "LEONA": "<lora:stLeona_XL-v1-000006:1>, stLeona,1girl,grey_hair,yellow_eyes,bangs,eyebrows_visible_through_hair,long_hair,swept_bangs,large_breasts,mature_woman,aged_up,",
    "MARIA": "<lora:stMaria_XL-v1-000005:1>, stMaria,1girl,bangle,bead_bracelet,bracelet,breasts,drill_hair,facial_mark,flower,hair_flower,hair_ornament,jewelry,medium_hair,nail_polish,pearl_bracelet,tattoo,wrist_scrunchie,wristband,",
    "MAURICE": "<lora:stMaurice_XL-v1:1>, stMaurice,1boy,black-framed_eyewear,eyebrows_visible_through_hair,glasses,over-rim_eyewear,semi-rimless_eyewear,under-rim_eyewear,mature male,aged_up,",
    "MEL": "<lora:stMel_XL-v1-000006:1>, stMel,1girl,blue_hair,ahoge,yellow_eyes,large_breasts,petite,",
    "MICHELLE": "<lora:stMichelle_XL-v1-000006:1>, stMichelle,1girl,brown_hair,brown_eyes,glasses,hair_ornament,hairclip,large_breasts,red-framed_eyewear,short_hair,",
    "NAOMI": "<lora:stNaomi_XL-v1:1>, stNaomi,1girl,blue_hair,yellow_eyes,bangs,eyebrows_visible_through_hair,hair_between_eyes,short_hair,mature female,medium_breasts,",
    "PHILA": "<lora:stPhila+Mina_XL-v1-000006:1>,stPhila,1girl,long_hair,wavy_hair,multicolored hair,heterochromia,green eyes,red eyes,blonde_hair,pink_hair,gradient hair,",
    "MINA": "<lora:stPhila+Mina_XL-v1-000006:1>,stMina,1girl,long_hair,wavy_hair,multicolored hair,heterochromia,green eyes,red eyes,blonde_hair,pink_hair,gradient hair,",
    "RILEY": "<lora:stRiley_XL-v1-000006:1>, stRiley,1boy,eyebrows_visible_through_hair,male_focus,brown_hair,brown_eyes,yellow_eyes,skinny,",
    "RITA": "<lora:stRita_XL-v1-000005:1>, stRita,1girl,drill_hair,eyebrows_visible_through_hair,hair_ornament,twin_drills,twintails,pink_hair,blue_eyes,",
    "SANDRA": "<lora:stSandra_XL-v1:.8>, stSandra,1girl pink_hair,blue_eyes,mole under eye,short_hair,mature_woman,aged up,huge_breasts,",
    "SETSUNA": "<lora:stSetsuna_XL-v1:1>, stSetsuna,1girl,(blue_hair:1.2),purple_eyes,medium_breasts,short_hair,braid,medium_breasts,",
    "TORI": "<lora:stTori_XL-v1-000006:1>, stTori,1girl,folded_ponytail,hair_ornament,hair_over_one_eye,large_breasts,grey_hair,yellow_eyes,",
    "VANESSA": "<lora:stVanessa_XL-v2:0.75>, stVanessa,1girl,red_hair,ponytail,medium_breasts,blue_eyes,chocker,",
    "YUI": "<lora:stYui_XL-v1-000005:1>, stYui,1girl,purple_hair,long_hair,straight_hair,braid,hair ribbon,red ribbon,purple_eyes,huge_breasts,",
    "ZOEY": "<lora:stZoey_XL-v1-000005:1>,stZoey,1girl,petite,small_breasts,blonde hair,long hair,hair bobbles,single braid,green eyes,energy,",

    "ST_SPRITE_STYLE_LOW": "<lora:STXL sprite v3-5:.2>,stsprtstle",
    "ST_SPRITE_STYLE_MID": "<lora:STXL sprite v3-5:.4>,stsprtstle",
    "ST_SPRITE_STYLE_HIGH": "<lora:STXL sprite v3-5:.6>,stsprtstle",
    "ST_SPRITE_STYLE_FULL": "<lora:STXL sprite v3-5:1.0>,stsprtstle",

    "ST_UNIFORM": "<lora:STXL sprite v3-5:.5>,stsprtstle, short sleeves, red necktie, blue vest, gold trim, grey background, solo, red skirt, pleated skirt, plaid skirt, short hair, standing, white shirt, dress shirt, double-breasted, straight hair, miniskirt, school emblem",

    "QUALITY": "score_9,score_8_up,score_7_up,score_6_up,score_5_up,score_4_up,source_anime,",
    "NEGATIVE": "fewer digits, extra body parts, censored, collage, logo, border, badhandv4, paintings, sketches, fingers, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), skin spots, acnes, skin blemishes, age spot, (outdoor:1.6), backlight,(ugly:1.331), (duplicate:1.331), (morbid:1.21), (mutilated:1.21), (tranny:1.331), mutated hands, (poorly drawn hands:1.5), blurry, (bad anatomy:1.21), (bad proportions:1.331), extra limbs, (disfigured:1.331), lowers, bad hands, missing fingers, extra digit, negative_hand-neg, backlighting,comic,greyscale,sketch,3d,fused fingers,missing digits,three_fingers,long_torso, ((realistic))"
}